name: "Pull Request Labeler"
# https://github.com/actions/labeler

on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GH_PAT }}"
