name: Update major tag

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Update major tag
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          export TAG_NAME="${GITHUB_REF##refs/tags/}"
          export TAG_MAJOR="${TAG_NAME%%.*}"
          git tag --force -a "${TAG_MAJOR}" -m "Release ${TAG_NAME}"
          git push --force origin "${TAG_MAJOR}"
